### ISSUE TITLE
Using Pytest's `getfixturevalue` function breaks Allure attachments during teardown.

### ISSUE THREAD

**Issue by pgoy-dod** [ScreenPyHQ/screenpy_adapter_allure#1] opened 2022-03-21 15:31 UTC
When an Actor is defined as a fixture and the Actor has some teardown Actions/Tasks after the `yield`, calling that Actor through Pytest's `getfixturevalue` function seems to break teardown reporting to Allure. `stdout` still works fine, but the `beat`s and file attachments do not show up in teardown.

What's going on?

**Comment by Scot3004** [comment] 2023-05-03 16:23
Do you have the source code for replicate this scenario?

**Comment by perrygoy** [comment] 2023-05-03 16:26
Unfortunately not anymore, but i think i can make a small one. One moment!

**Comment by perrygoy** [comment] 2023-05-03 17:14
Huh, actually, it looks like this might have been a real bug in Allure or Pytest or something that got fixed, because i can't reproduce it! Here's the code that previously might have reproduced this problem:

```python
# test.py

from collections.abc import Generator
from pathlib import Path

import allure
import pytest
from screenpy import Actor, AnActor, beat, the_narrator
from screenpy.actions import AttachAFile
from screenpy_adapter_allure import AllureAdapter


the_narrator.attach_adapter(AllureAdapter())


class SaySomethingWillYa:
    """Say something!"""

    def __init__(self, something: str) -> None:
        self.something = something

    @beat("{} says something: {something}")
    def perform_as(self, _: Actor) -> None:
        pass


@pytest.fixture
def Tessa() -> Generator:
    the_actor = AnActor.named("Tessa")
    the_actor.attempts_to(SaySomethingWillYa("during setup!"))
    yield the_actor
    the_actor.attempts_to(SaySomethingWillYa("during teardown!"))
    the_actor.exit()


def test_teardown_logging(request: pytest.FixtureRequest) -> None:
    Tessa: Actor = request.getfixturevalue("Tessa")
    Tessa.has_ordered_cleanup_tasks(
        SaySomethingWillYa("during cleanup!"),
        AttachAFile(Path("./test.py"), attachment_type=allure.attachment_type.TEXT)
    )

    Tessa.attempts_to(SaySomethingWillYa("during the test!"))
```

To run that, save it somewhere as `test.py`, then you'd do:
```bash
python -m venv env
source env/bin/activate
pip install "screenpy[allure]" pytest
python -m pytest test.py --log-cli-level=info --alluredir=./allure
allure serve ./allure
```

And here's the report:
<img width="649" alt="Screenshot 2023-05-03 at 12 12 47 PM" src="https://user-images.githubusercontent.com/27103725/235990787-85f1e3f8-dec6-4c9a-8345-2d4db7643826.png">

So... i guess we can close this one as can't reproduce! Thanks for the prod, @Scot3004!

**Closed as completed by perrygoy** 2023-05-03 17:14 UTC
